// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package grpc_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateId) Reset()         { *m = CreateId{} }
func (m *CreateId) String() string { return proto.CompactTextString(m) }
func (*CreateId) ProtoMessage()    {}
func (*CreateId) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0}
}

func (m *CreateId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateId.Unmarshal(m, b)
}
func (m *CreateId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateId.Marshal(b, m, deterministic)
}
func (m *CreateId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateId.Merge(m, src)
}
func (m *CreateId) XXX_Size() int {
	return xxx_messageInfo_CreateId.Size(m)
}
func (m *CreateId) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateId.DiscardUnknown(m)
}

var xxx_messageInfo_CreateId proto.InternalMessageInfo

func (m *CreateId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CustomerCreatereq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender               int32    `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	CustomerName         string   `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerId           int32    `protobuf:"varint,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerCreatereq) Reset()         { *m = CustomerCreatereq{} }
func (m *CustomerCreatereq) String() string { return proto.CompactTextString(m) }
func (*CustomerCreatereq) ProtoMessage()    {}
func (*CustomerCreatereq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{1}
}

func (m *CustomerCreatereq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerCreatereq.Unmarshal(m, b)
}
func (m *CustomerCreatereq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerCreatereq.Marshal(b, m, deterministic)
}
func (m *CustomerCreatereq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerCreatereq.Merge(m, src)
}
func (m *CustomerCreatereq) XXX_Size() int {
	return xxx_messageInfo_CustomerCreatereq.Size(m)
}
func (m *CustomerCreatereq) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerCreatereq.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerCreatereq proto.InternalMessageInfo

func (m *CustomerCreatereq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerCreatereq) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *CustomerCreatereq) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *CustomerCreatereq) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateId)(nil), "grpc_pb.CreateId")
	proto.RegisterType((*CustomerCreatereq)(nil), "grpc_pb.CustomerCreatereq")
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_9efa92dae3d6ec46) }

var fileDescriptor_9efa92dae3d6ec46 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2e, 0x2d, 0x2e,
	0xc9, 0xcf, 0x4d, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x2a, 0x48,
	0x8e, 0x2f, 0x48, 0x52, 0x92, 0xe2, 0xe2, 0x70, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0xf5, 0x4c, 0x11,
	0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x51,
	0x6a, 0x67, 0xe4, 0x12, 0x74, 0x86, 0xea, 0x83, 0x28, 0x2a, 0x4a, 0x2d, 0x14, 0x12, 0xe1, 0x62,
	0x2d, 0xc8, 0xc8, 0xcf, 0x4b, 0x05, 0x2b, 0xe4, 0x0c, 0x82, 0x70, 0x84, 0xc4, 0xb8, 0xd8, 0xd2,
	0x53, 0xf3, 0x52, 0x52, 0x8b, 0x24, 0x98, 0xc0, 0xfa, 0xa1, 0x3c, 0x21, 0x65, 0x2e, 0x5e, 0x98,
	0xd5, 0xf1, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0xcc, 0x60, 0x5d, 0x3c, 0x30, 0x41, 0xbf, 0xc4, 0xdc,
	0x54, 0x21, 0x79, 0x2e, 0x6e, 0xb8, 0xa2, 0xcc, 0x14, 0x09, 0x16, 0xb0, 0x09, 0x5c, 0x30, 0x21,
	0xcf, 0x14, 0x23, 0x2f, 0x2e, 0x7e, 0x98, 0x43, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85,
	0xcc, 0xb9, 0xd8, 0x20, 0x6e, 0x12, 0x92, 0xd2, 0x83, 0x7a, 0x46, 0x0f, 0xc3, 0xb1, 0x52, 0x82,
	0x08, 0x39, 0xa8, 0x2f, 0x93, 0xd8, 0xc0, 0x21, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0x98, 0xc1, 0xd8, 0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	Create(ctx context.Context, in *CustomerCreatereq, opts ...grpc.CallOption) (*CreateId, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) Create(ctx context.Context, in *CustomerCreatereq, opts ...grpc.CallOption) (*CreateId, error) {
	out := new(CreateId)
	err := c.cc.Invoke(ctx, "/grpc_pb.CustomerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	Create(context.Context, *CustomerCreatereq) (*CreateId, error)
}

// UnimplementedCustomerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (*UnimplementedCustomerServiceServer) Create(ctx context.Context, req *CustomerCreatereq) (*CreateId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerCreatereq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_pb.CustomerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).Create(ctx, req.(*CustomerCreatereq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_pb.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomerService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
