// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package grpc_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserCreateReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	RoleId               int32    `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateReq) Reset()         { *m = UserCreateReq{} }
func (m *UserCreateReq) String() string { return proto.CompactTextString(m) }
func (*UserCreateReq) ProtoMessage()    {}
func (*UserCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateReq.Unmarshal(m, b)
}
func (m *UserCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateReq.Marshal(b, m, deterministic)
}
func (m *UserCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateReq.Merge(m, src)
}
func (m *UserCreateReq) XXX_Size() int {
	return xxx_messageInfo_UserCreateReq.Size(m)
}
func (m *UserCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateReq proto.InternalMessageInfo

func (m *UserCreateReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserCreateReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *UserCreateReq) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserCreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserListReq struct {
	PageIndex            int32    `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword              string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListReq) Reset()         { *m = UserListReq{} }
func (m *UserListReq) String() string { return proto.CompactTextString(m) }
func (*UserListReq) ProtoMessage()    {}
func (*UserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListReq.Unmarshal(m, b)
}
func (m *UserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListReq.Marshal(b, m, deterministic)
}
func (m *UserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListReq.Merge(m, src)
}
func (m *UserListReq) XXX_Size() int {
	return xxx_messageInfo_UserListReq.Size(m)
}
func (m *UserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserListReq proto.InternalMessageInfo

func (m *UserListReq) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *UserListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *UserListReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type UserListResp struct {
	Data                 []*UserListResp_One `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total                int64               `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserListResp) Reset()         { *m = UserListResp{} }
func (m *UserListResp) String() string { return proto.CompactTextString(m) }
func (*UserListResp) ProtoMessage()    {}
func (*UserListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResp.Unmarshal(m, b)
}
func (m *UserListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResp.Marshal(b, m, deterministic)
}
func (m *UserListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResp.Merge(m, src)
}
func (m *UserListResp) XXX_Size() int {
	return xxx_messageInfo_UserListResp.Size(m)
}
func (m *UserListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResp proto.InternalMessageInfo

func (m *UserListResp) GetData() []*UserListResp_One {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserListResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type UserListResp_One struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender               int32    `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	RoleId               int32    `protobuf:"varint,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResp_One) Reset()         { *m = UserListResp_One{} }
func (m *UserListResp_One) String() string { return proto.CompactTextString(m) }
func (*UserListResp_One) ProtoMessage()    {}
func (*UserListResp_One) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3, 0}
}

func (m *UserListResp_One) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResp_One.Unmarshal(m, b)
}
func (m *UserListResp_One) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResp_One.Marshal(b, m, deterministic)
}
func (m *UserListResp_One) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResp_One.Merge(m, src)
}
func (m *UserListResp_One) XXX_Size() int {
	return xxx_messageInfo_UserListResp_One.Size(m)
}
func (m *UserListResp_One) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResp_One.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResp_One proto.InternalMessageInfo

func (m *UserListResp_One) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserListResp_One) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserListResp_One) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserListResp_One) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserListResp_One) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func init() {
	proto.RegisterType((*UserId)(nil), "grpc_pb.UserId")
	proto.RegisterType((*UserCreateReq)(nil), "grpc_pb.UserCreateReq")
	proto.RegisterType((*UserListReq)(nil), "grpc_pb.UserListReq")
	proto.RegisterType((*UserListResp)(nil), "grpc_pb.UserListResp")
	proto.RegisterType((*UserListResp_One)(nil), "grpc_pb.UserListResp.One")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x4e, 0xfa, 0x40,
	0x14, 0xc5, 0xd3, 0x0f, 0xca, 0x9f, 0xcb, 0x5f, 0x4d, 0x6e, 0x10, 0x47, 0x8c, 0x09, 0xe9, 0x8a,
	0x8d, 0x4d, 0x84, 0x47, 0x70, 0xd5, 0xc4, 0x84, 0xa4, 0xc4, 0x75, 0x53, 0x98, 0x1b, 0x1c, 0xc5,
	0x76, 0x98, 0x0e, 0x7e, 0xf0, 0x7e, 0xbe, 0x97, 0x99, 0x19, 0x90, 0x62, 0xd8, 0xf5, 0x9c, 0xde,
	0xf6, 0xcc, 0xf9, 0xdd, 0x01, 0xd8, 0xd4, 0xa4, 0x12, 0xa9, 0x2a, 0x5d, 0x61, 0x7b, 0xa9, 0xe4,
	0x22, 0x97, 0xf3, 0x98, 0x41, 0xf4, 0x54, 0x93, 0x4a, 0x39, 0x9e, 0x83, 0x2f, 0x38, 0xf3, 0x86,
	0xde, 0xa8, 0x95, 0xf9, 0x82, 0xc7, 0x2f, 0x70, 0x66, 0xde, 0x3c, 0x28, 0x2a, 0x34, 0x65, 0xb4,
	0xc6, 0x1e, 0xb4, 0xe4, 0x73, 0x55, 0x92, 0x9d, 0xe9, 0x64, 0x4e, 0xe0, 0x15, 0xb4, 0x55, 0xb5,
	0xa2, 0x5c, 0x70, 0xe6, 0xdb, 0x6f, 0x23, 0x23, 0x53, 0x8e, 0x7d, 0x88, 0x96, 0x54, 0x72, 0x52,
	0x2c, 0x70, 0xbe, 0x53, 0x88, 0x10, 0x96, 0xc5, 0x1b, 0xb1, 0xd0, 0xfe, 0xc5, 0x3e, 0xc7, 0x0b,
	0xe8, 0x9a, 0xac, 0x47, 0x51, 0x6b, 0x93, 0x74, 0x0b, 0x20, 0x8b, 0x25, 0xe5, 0xa2, 0xe4, 0xf4,
	0xb9, 0x3b, 0x52, 0xc7, 0x38, 0xa9, 0x31, 0xf0, 0x06, 0xac, 0xc8, 0x6b, 0xb1, 0xa5, 0x5d, 0xe8,
	0x3f, 0x63, 0xcc, 0xc4, 0x96, 0x90, 0x41, 0xfb, 0x95, 0xbe, 0x3e, 0x2a, 0xc5, 0x6d, 0x6e, 0x27,
	0xdb, 0xcb, 0xf8, 0xdb, 0x83, 0xff, 0x87, 0x94, 0x5a, 0xe2, 0x1d, 0x84, 0xbc, 0xd0, 0x05, 0xf3,
	0x86, 0xc1, 0xa8, 0x3b, 0xbe, 0x4e, 0x76, 0x4c, 0x92, 0xe6, 0x50, 0x32, 0x2d, 0x29, 0xb3, 0x63,
	0xa6, 0xbf, 0xae, 0x74, 0xb1, 0xb2, 0x91, 0x41, 0xe6, 0xc4, 0x40, 0x42, 0x30, 0x2d, 0xe9, 0x2f,
	0xbd, 0x03, 0x2c, 0xbf, 0x09, 0x6b, 0xdf, 0x3d, 0x38, 0x74, 0x6f, 0x70, 0x0a, 0x8f, 0x38, 0x35,
	0xc0, 0xb6, 0x9a, 0x60, 0xc7, 0x1b, 0x07, 0x6b, 0x46, 0xea, 0x5d, 0x2c, 0x08, 0xef, 0x21, 0x72,
	0x3b, 0xc2, 0xfe, 0x51, 0x83, 0xdf, 0xc5, 0x0d, 0x2e, 0x8e, 0xfc, 0x94, 0xe3, 0x04, 0x42, 0xd3,
	0x0f, 0x7b, 0x27, 0x2a, 0xaf, 0x07, 0x97, 0x27, 0x41, 0xcc, 0x23, 0x7b, 0x73, 0x26, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xbc, 0x79, 0xcc, 0x00, 0x47, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*UserId, error)
	List(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*UserId, error) {
	out := new(UserId)
	err := c.cc.Invoke(ctx, "/grpc_pb.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) List(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	out := new(UserListResp)
	err := c.cc.Invoke(ctx, "/grpc_pb.UserService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *UserCreateReq) (*UserId, error)
	List(context.Context, *UserListReq) (*UserListResp, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *UserCreateReq) (*UserId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) List(ctx context.Context, req *UserListReq) (*UserListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_pb.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*UserCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_pb.UserService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).List(ctx, req.(*UserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
