// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.0
// source: user_enum.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 性别
type Gender int32

const (
	Gender_GENDER_UNKNOW Gender = 0 // 未填写
	Gender_GENDER_MALE   Gender = 1 // 男性
	Gender_GENDER_FEMALE Gender = 2 // 女性
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNKNOW",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNKNOW": 0,
		"GENDER_MALE":   1,
		"GENDER_FEMALE": 2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_user_enum_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_user_enum_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_user_enum_proto_rawDescGZIP(), []int{0}
}

// 会员等级
type CustomerLevel int32

const (
	CustomerLevel_CUSTOMER_LEVEL_ORDINARY CustomerLevel = 0  // 普通
	CustomerLevel_CUSTOMER_LEVEL_BRONZE   CustomerLevel = 10 // 青铜
	CustomerLevel_CUSTOMER_LEVEL_SILVER   CustomerLevel = 20 // 白银
	CustomerLevel_CUSTOMER_LEVEL_GOLD     CustomerLevel = 30 // 黄金
)

// Enum value maps for CustomerLevel.
var (
	CustomerLevel_name = map[int32]string{
		0:  "CUSTOMER_LEVEL_ORDINARY",
		10: "CUSTOMER_LEVEL_BRONZE",
		20: "CUSTOMER_LEVEL_SILVER",
		30: "CUSTOMER_LEVEL_GOLD",
	}
	CustomerLevel_value = map[string]int32{
		"CUSTOMER_LEVEL_ORDINARY": 0,
		"CUSTOMER_LEVEL_BRONZE":   10,
		"CUSTOMER_LEVEL_SILVER":   20,
		"CUSTOMER_LEVEL_GOLD":     30,
	}
)

func (x CustomerLevel) Enum() *CustomerLevel {
	p := new(CustomerLevel)
	*p = x
	return p
}

func (x CustomerLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomerLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_user_enum_proto_enumTypes[1].Descriptor()
}

func (CustomerLevel) Type() protoreflect.EnumType {
	return &file_user_enum_proto_enumTypes[1]
}

func (x CustomerLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomerLevel.Descriptor instead.
func (CustomerLevel) EnumDescriptor() ([]byte, []int) {
	return file_user_enum_proto_rawDescGZIP(), []int{1}
}

var File_user_enum_proto protoreflect.FileDescriptor

var file_user_enum_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x64, 0x6b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2a, 0x3f, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x11, 0x0a, 0x0d,
	0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x45, 0x4d, 0x41, 0x4c,
	0x45, 0x10, 0x02, 0x2a, 0x7b, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x45, 0x52,
	0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x4f, 0x52, 0x44, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10,
	0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x45, 0x52, 0x5f, 0x4c, 0x45,
	0x56, 0x45, 0x4c, 0x5f, 0x42, 0x52, 0x4f, 0x4e, 0x5a, 0x45, 0x10, 0x0a, 0x12, 0x19, 0x0a, 0x15,
	0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x45, 0x52, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x53,
	0x49, 0x4c, 0x56, 0x45, 0x52, 0x10, 0x14, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x45, 0x52, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x47, 0x4f, 0x4c, 0x44, 0x10, 0x1e,
	0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77,
	0x61, 0x6e, 0x67, 0x7a, 0x68, 0x65, 0x31, 0x39, 0x39, 0x31, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x73, 0x64, 0x6b, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_user_enum_proto_rawDescOnce sync.Once
	file_user_enum_proto_rawDescData = file_user_enum_proto_rawDesc
)

func file_user_enum_proto_rawDescGZIP() []byte {
	file_user_enum_proto_rawDescOnce.Do(func() {
		file_user_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_enum_proto_rawDescData)
	})
	return file_user_enum_proto_rawDescData
}

var file_user_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_enum_proto_goTypes = []interface{}{
	(Gender)(0),        // 0: grpc_sdk.common.Gender
	(CustomerLevel)(0), // 1: grpc_sdk.common.CustomerLevel
}
var file_user_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_enum_proto_init() }
func file_user_enum_proto_init() {
	if File_user_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_enum_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_enum_proto_goTypes,
		DependencyIndexes: file_user_enum_proto_depIdxs,
		EnumInfos:         file_user_enum_proto_enumTypes,
	}.Build()
	File_user_enum_proto = out.File
	file_user_enum_proto_rawDesc = nil
	file_user_enum_proto_goTypes = nil
	file_user_enum_proto_depIdxs = nil
}
